<a href="https://colab.research.google.com/github/Samuel-Njoroge/Numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY.**
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays

In [1]:
#Importing the library
import numpy as np

**Arrays - An arrangement of objects, pictures, or numbers in rows and columns**

In [2]:
#Creating arrays
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

**Multi-dimensional Arrays**

In [5]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Randomly generated numbers**

In [9]:
np.random.seed(10)
np.random.rand(5, 2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [10]:
np.random.seed(10)
np.random.randn(5, 2)

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021]])

**Element wise operations**

In [11]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [12]:
a * 2

array([0, 2, 4, 6, 8])

In [13]:
a ** 2

array([ 0,  1,  4,  9, 16])

**Summary Statistics**

In [ ]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
#Mean
np.mean(a)

2.0

In [15]:
#Standard deviation
np.std(a)

1.4142135623730951

In [16]:
#Median
np.median(a)

2.0